FROM node:20 as builder
WORKDIR /app/chat-ui/
COPY ./app/chat-ui/package*.json ./
RUN npm install
COPY ./app/chat-ui/ .
RUN npm run build

FROM node:20 as runner
WORKDIR /app/chat-ui/
COPY ./app/chat-ui/ .
COPY --from=builder /app/chat-ui/public ./public
# COPY --from=builder /app/chat-ui/.next/standalone ./
COPY --from=builder /app/chat-ui/.next/static ./.next/static
EXPOSE 3000
RUN ls
CMD ["node", "server.js"]
# ENTRYPOINT ["node"]